# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "g_sectioned_shower"
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["C. Jason Harrelson (midas)"]
  s.date = "2012-09-28"
  s.description = "A Guilded (http://github.com/midas/guilded/tree/master) component that creates adaptable show (detail) views of a single ActiveRecord object."
  s.email = "jason@lookforwardenterprises.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "History.txt",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "g_sectioned_shower.gemspec",
    "lib/g_sectioned_shower.rb",
    "lib/g_sectioned_shower/view_helpers.rb",
    "script/console",
    "script/destroy",
    "script/generate",
    "tasks/rspec.rake",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/midas/tester"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A Guilded (http://github.com/midas/guilded/tree/master) component that creates adaptable show (detail) views of a single ActiveRecord object."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 2.2.0"])
      s.add_runtime_dependency(%q<guilded>, [">= 1.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 2.2.0"])
      s.add_dependency(%q<guilded>, [">= 1.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 2.2.0"])
    s.add_dependency(%q<guilded>, [">= 1.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

